### ISSUE TITLE
"Mitarbeiter hinzufügen"-Ansicht implementieren

### ISSUE THREAD

**Issue by PowerOfCreation** [PowerOfCreation/E1Ressourcenverwaltung#10]
Ein Formular wie im Mockup, welches die Formular Werte per POST überträgt.

**Comment by PowerOfCreation** [comment]
20820df

**Comment by scuuuu** [comment]
Die Ansicht verbessert, Passwortvalidierung hinzugefügt.
Mindestanforderungen an das Passwort müssen noch implementiert werden
