### ISSUE TITLE
CSS: Design verbessern

### ISSUE THREAD

**Issue by PowerOfCreation** [PowerOfCreation/E1Ressourcenverwaltung#102]
Ziel: Ähnliches Design zu https://design-factory.t-systems-mms.com/home.html

**Comment by Vinh911** [comment]
ad07bc7020caf76afbae637bacc6b0c973a8dcd0

**Comment by Vinh911** [comment]
#118

**Comment by Vinh911** [comment]
![WhatsApp Image 2022-06-12 at 13 12 18](https://user-images.githubusercontent.com/49061616/173230395-70e0933f-72e1-4978-af5f-f00288d2414d.jpeg)
