### ISSUE TITLE
Mitarbeiteransicht: Löschen Funktionalität

### ISSUE THREAD

**Issue by PowerOfCreation** [PowerOfCreation/E1Ressourcenverwaltung#103]
Ziel: Nachdem ein Mitarbeiter angeklickt wurde, soll es möglich sein diesen zu löschen. Dazu soll eine Bestätigung kommen. Sämtliche Status müssen ebenfalls gelöscht werden. 
Wo: webserver/mitarbeiter/index.php

**Comment by Vinh911** [comment]
<img width="693" alt="Screen Shot 2022-06-16 at 15 07 20" src="https://user-images.githubusercontent.com/49061616/174076401-f329fb12-5210-4b41-9323-705a2f4c6e3a.png">
Beim löschen des Mitarbeiters wirft das file database_structure immer einen Fehler. Wieso muss diese eigentlich überall included werden?

**Comment by PowerOfCreation** [comment]
Das passiert nur wenn du den letzten Mitarbeiter löschst oder?

**Comment by PowerOfCreation** [comment]
@Vinh911

**Comment by Vinh911** [comment]
alles klar, spuckt keinen Fehler mehr aus
