### ISSUE TITLE
Softwaredokumentation generieren

### ISSUE THREAD

**Issue by PowerOfCreation** [PowerOfCreation/E1Ressourcenverwaltung#137]

**Comment by scuuuu** [comment]
<img width="937" alt="Bildschirmfoto 2022-06-27 um 19 57 22" src="https://user-images.githubusercontent.com/85530038/176005684-141935a7-9069-461a-b5e9-05e1a01b7090.png">

https://openbase.com/categories/js/best-javascript-documentation-generator-libraries

https://esdoc.org
