### ISSUE TITLE
Beleg korrigieren

### ISSUE THREAD

**Issue by PowerOfCreation** [PowerOfCreation/E1Ressourcenverwaltung#29]
Ziel: Fehler die angestrichen wurden werden ausgebessert.

**Comment by PowerOfCreation** [comment]
Siehe #31

**Comment by s82068** [comment]
Bewertung: wie bei den issues sichergestellt wird, dass es "gut" ist bzw erfüllt

**Comment by PowerOfCreation** [comment]
Geht es darum wie wir das in unserer Gruppe machen? Wir haben bei den Issues eine Zielstellung drinnen bzw. unsere Issues sind User Stories. Wenn die Software so funktioniert wie im Issue als Zielstellung beschrieben, dann ist es fertig. Weiterhin sollte über jeden committ bzw. Änderung jeder zumindest grob drüberschauen.
