### ISSUE TITLE
Mitarbeiter hinzufügen check der E-Mail

### ISSUE THREAD

**Issue by PowerOfCreation** [PowerOfCreation/E1Ressourcenverwaltung#33]
Wo: /registration/index.html
Ziel: Prüfen des E-Mail Formats mit einem Regex im Front-End + Backend

**Comment by Vinh911** [comment]
Das ist das issue für login/registration oder?

**Comment by PowerOfCreation** [comment]
Das ist ein Issue um bei der Registrierung zu prüfen, ob die eingegebene E-Mail valide ist

**Comment by Vinh911** [comment]
#1cc6bd3fc41ecea8d64e1b68ef3c2fc847b37130

**Comment by Vinh911** [comment]
1cc6bd3fc41ecea8d64e1b68ef3c2fc847b37130

**Comment by Vinh911** [comment]
> > Das ist das issue für login/registration oder?
> 
> @Vinh911 Das ist ein Issue um bei der Registrierung zu prüfen, ob die eingegebene E-Mail valide ist

Soll ich für registration/login ein neues issue erstellen?

**Comment by PowerOfCreation** [comment]
> > > Das ist das issue für login/registration oder?
> > 
> > 
> > @Vinh911 Das ist ein Issue um bei der Registrierung zu prüfen, ob die eingegebene E-Mail valide ist
> 
> Soll ich für registration/login ein neues issue erstellen?

Hat erstmal nicht so die Priorität. Müssen erstmal die Status- und Wochenanzeige fertig machen. Wenn sich das nicht sinnvoll parallelisieren lässt kann man Issues für Login aufmachen, aber noch haben wir ja offene andere Issues.

**Comment by PowerOfCreation** [comment]
Falls noch nicht getan muss die E-Mail auch im Back-End geprüft werden: https://www.delftstack.com/howto/php/php-validation-email/
