### ISSUE TITLE
API: Status der Kalenderwoche

### ISSUE THREAD

**Issue by PowerOfCreation** [PowerOfCreation/E1Ressourcenverwaltung#49]
Ziel: Es soll einen neuen Endpunkt geben, welchem per GET eine Kalenderwoche + Jahr übergeben wird und daraufhin werden in JSON sämtliche Status in dieser Woche zurückgeliefert. Werden keine Parameter übergeben soll die aktuelle Woche zurückgeliefert werden.
Beispiel:
/api/get_all_weekly_status.php?calenderWeek=17&year=2022
Response:
[[user: 2, day: 25.04.2022, project: 1], [user: ....]]

Wo: neue Datei /api/get_all_weekly_status.php

**Comment by Vinh911** [comment]
@PowerOfCreation gibt es eine Möglichkeit mich mit einem Datenbank management system in die DB einzuloggen?

**Comment by PowerOfCreation** [comment]
> @PowerOfCreation gibt es eine Möglichkeit mich mit einem Datenbank management system in die DB einzuloggen?

@Vinh911 Ja, du kannst einen beliebigen Client wie z.B. DBeaver nutzen und dich mit der DB verbinden. Die Logindaten findest du in src/config/credentials.php.

**Comment by Vinh911** [comment]
$host = 'database';
// Database use name
$user = 'MYSQL_USER';

//database user password
$pass = 'MYSQL_PASSWORD';

$dbname = 'MY_DATABASE';


habe auch als host localhost:3306 probiert. beides geht nicht.

**Comment by PowerOfCreation** [comment]
Sobald du docker-compose up bzw docker compose up ausgeführt hast läuft auf deiner Maschine ein Webserver und ein Datenbankserver. In der Konsole sollte dann auch die Ausgabe stehen wie beide starten. Du kannst das auch überprüfen indem du die belegten Ports überprüfst. Dazu einfach mal für dein Betriebssystem googlen wie man die vergebenen Ports anzeigen lässt.

**Comment by Vinh911** [comment]
![Screen Shot 2022-05-07 at 19 40 29](https://user-images.githubusercontent.com/49061616/167265583-6cfa1558-27f1-4879-a164-93e7c86ba105.png)
![Screen Shot 2022-05-07 at 19 40 37](https://user-images.githubusercontent.com/49061616/167265589-2419099c-c4e1-497b-b771-6c8d622c5b83.png)
db container ist online, aber kann mich nicht connecten 😅

**Comment by PowerOfCreation** [comment]
Zeigt dein Betriebssystem den Port ebenfalls als belegt an?

**Comment by Vinh911** [comment]
![Screen Shot 2022-05-07 at 20 10 22](https://user-images.githubusercontent.com/49061616/167266610-8a076aec-8e19-4577-98b9-49e9613008cd.png)
Ja

**Comment by Vinh911** [comment]
341d878567e8bab0d1ea1c33e0f2ea9b38f523e8
Eingabe:
http://localhost/api/get_all_weekly_status.php?calendarWeek=18&year=2022
Ausgabe:
[{"StatusId":4,"UserId":1,"ProjectId":221,"Day":"2022-05-06"},{"StatusId":5,"UserId":1,"ProjectId":221,"Day":"2022-05-03"},{"StatusId":6,"UserId":1,"ProjectId":221,"Day":"2022-05-05"}

@PowerOfCreation ist der Output so in Ordnung, oder soll ich den noch wie im Issue beschreiben konvertiert?

**Comment by PowerOfCreation** [comment]
> [341d878](https://github.com/PowerOfCreation/E1Ressourcenverwaltung/commit/341d878567e8bab0d1ea1c33e0f2ea9b38f523e8) Eingabe: http://localhost/api/get_all_weekly_status.php?calendarWeek=18&year=2022 Ausgabe: [{"StatusId":4,"UserId":1,"ProjectId":221,"Day":"2022-05-06"},{"StatusId":5,"UserId":1,"ProjectId":221,"Day":"2022-05-03"},{"StatusId":6,"UserId":1,"ProjectId":221,"Day":"2022-05-05"}
> 
> @PowerOfCreation ist der Output so in Ordnung, oder soll ich den noch wie im Issue beschreiben konvertiert?

Sieht gut aus und vermutlich auch sinnvoller

**Comment by PowerOfCreation** [comment]
Funktioniert, jedoch bitte noch die Kommentare zu dem commits beachten. GET Aufrufe müssen noch mit htmlspecialchars gewrappt werden, cURL Aufrufe ersetzen durch include+Funktionsaufrufe und das Jahr muss noch beachtet werden.

**Comment by PowerOfCreation** [comment]
#64
