### ISSUE TITLE
API: Erweiterung um das Jahr

### ISSUE THREAD

**Issue by PowerOfCreation** [PowerOfCreation/E1Ressourcenverwaltung#50]
Ziel: /api/get_calendar_week.php soll auch das betreffende Jahr zurückliefern.
Wo: /api/get_calendar_week.php

**Comment by Vinh911** [comment]
{
"calenderWeek":"16",
"weekdays":["2022-04-18","2022-04-19","2022-04-20","2022-04-21","2022-04-22","2022-04-23","2022-04-24"],
year: "2022"
}

Ich würde das Jahr als weiteren Key/Value-pair anhängen.
Einfachster Weg wäre es von einem Wochentag das Jahr zu extrahieren. Soll ich auch überprüfen ob in der Woche ein Jahreswechsel vorkommt und in dem Fall z.B. 2022/2023 übergeben?

**Comment by PowerOfCreation** [comment]
Ja genau. Ich glaube es würde erstmal reichen das Jahr des ersten
Wochentages nochmal als weiteres Wertpaar zu liefern

**Comment by Vinh911** [comment]
0741db54fb195c8d7780ad6072547f03db87dae2
