### ISSUE TITLE
Status anzeigen

### ISSUE THREAD

**Issue by PowerOfCreation** [PowerOfCreation/E1Ressourcenverwaltung#51]
Ziel: Beim laden der index.php der Wochenansicht sollen die Status der Mitarbeiter geladen werden. Dies soll mit Ajax realisiert werden und später generalisiert werden können um auch von der vorherigen oder einer beliebigen Kalenderwoche den Status anzuzeigen. Denkbar ist ein Aufruf an die /api/get_calendar_week.php und anschließend mit dem erhaltenen Wert einen Ajax Aufruf an /api/get_all_weekly_status.php. Anschließend werden die Status als <div> in den betreffenden Zellen angelegt.
Wo: index.php der Wochenansicht

Hängt ab von #49 #50

**Comment by Vinh911** [comment]
Wo kommt das js file für index.php hin und wie soll es benannt werden?

**Comment by PowerOfCreation** [comment]
Wir haben dafür schon eine JS Datei: src/webserver/js/weekly-report.js

**Comment by Vinh911** [comment]
Das Grundgerüst der Tabelle wird in index.php erstellt, die Tabelle wird dann in JS gefüllt. Ich habe gerade einige Schwierigkeiten bei der Umsetzung, da ich für das mapping der Daten den Cells eine id mit dem Datum des jeweiligen Tages geben würde.
Kann ich die Tabelle entweder nur in php oder nur in JS mit Daten füllen? Aktuell ziehen wir die Usernames in der Index.php, aber die Status in JS.

**Comment by PowerOfCreation** [comment]
#64 Das issue ist fast vollständig bearbeitet es fehl lediglich noch die Anzeige des Projektnamen anstatt der ProjectId. Vielleicht kann dies jemand anderes vervollständigen?

**Comment by Vinh911** [comment]
<img width="669" alt="Screen Shot 2022-05-21 at 16 39 21" src="https://user-images.githubusercontent.com/49061616/169656543-e54e59c3-6e16-42f9-8945-6ad417c8fea9.png">
Projektname wird mit angezeigt :)
