### ISSUE TITLE
API: Einfügen eines neuen Status

### ISSUE THREAD

**Issue by PowerOfCreation** [PowerOfCreation/E1Ressourcenverwaltung#52]
Ziel: Es soll einen neuen Endpunkt geben mit welchem ein neuer Status eingefügt werden kann.
Beispiel:
Aufruf: /api/add_status.php?user=1&project=2&date=2022-04-25
Daraufhin wird true zurückgeliefert, sofern das einfügen in die DB erfolgreich war.
Wo: Neue Datei api/add_status.php

**Comment by Vinh911** [comment]
643480b3894b482df90d98a6116e7c48d2c4eeda
Aufruf: /api/add_status.php?user=1&project=2&date="2022-04-25"
date muss als string übergeben werden, sonst gibt es Probleme mit der Datenbank.

**Comment by PowerOfCreation** [comment]
Das ist in Ordnung. Wird eine Fehlerbehandlung durchgeführt bzw. eine Fehlermeldung ausgegeben, wenn etwas nicht stimmt?

**Comment by Vinh911** [comment]
Ja, falls nicht alle parameter übergeben werden oder wenn die anfrage zur Datenbank nicht funktioniert, wird jeweils eine Fehlermeldung ausgegeben.

**Comment by PowerOfCreation** [comment]
> Ja, falls nicht alle parameter übergeben werden oder wenn die anfrage zur Datenbank nicht funktioniert, wird jeweils eine Fehlermeldung ausgegeben.

Mache ich etwas falsch? Aufruf: http://localhost/api/add_status.php?user=1&project=2&date=%222022-04-25%22
Ergebnis: Status added
DBeaver: 
![image](https://user-images.githubusercontent.com/24482177/167594811-b081f993-d08a-4de7-a73f-bb8ec8b09682.png)

Hab ein paarmal F5 gedrückt, deswegen soviele... Das mit dem Day hat irgendwie nicht ganz geklappt. Ich glaube die Datenbankstruktur war auch nicht so intelligent gewählt. Ich mach ein neues issue um StatusID zu entfernen und den Primary Key aus den 3 anderen Spalten zu bilden.

**Comment by PowerOfCreation** [comment]
Ich vermute es liegt daran, dass das bind_param('iis') sein muss.

**Comment by Vinh911** [comment]
ich hab das eigentlich getestet. ich hab vorgestern ein paar commits reverted. Es könnte sein, dass diese Änderung auch dabei war. Es müsste nämlich wie von dir beschrieben 'iis' sein.

**Comment by PowerOfCreation** [comment]
#64
