### ISSUE TITLE
Projekt erstellen in User_Project übernehmen

### ISSUE THREAD

**Issue by justusbeck** [PowerOfCreation/E1Ressourcenverwaltung#55]
Ziel: Sobald ein Projekt erstellt wird, soll der angegebene ProjectOwner automatisch als Projektmitglied in die Tabelle User_Project eingetragen werden.
Wo: project/newproject/index.php

**Comment by Vinh911** [comment]
@PowerOfCreation hier lieber erstmal das pk issue lösen oder?

**Comment by PowerOfCreation** [comment]
> @PowerOfCreation hier lieber erstmal das pk issue lösen oder?

Könnte sinnvoll sein, ja. Für das issue am besten eine PHP Funktion erstellen in der API Datei, um neue Nutzer einem Projekt hinzuzufügen und dann wieder den Trick, um zu prüfen ob die Datei inkludiert ist oder direkt aufgerufen wird. Vielleicht gibt es das aber auch schon?

**Comment by Vinh911** [comment]
#117
