### ISSUE TITLE
Manuelle Qualitätsprüfung

### ISSUE THREAD

**Issue by PowerOfCreation** [PowerOfCreation/E1Ressourcenverwaltung#65]
Ziel: Ausgiebiges Testen des bestehenden Projektes mithilfe eines Webbrowsers.

**Comment by s80433** [comment]
-**Fehlermeldung nach Dateneingabe im "Projekt Erstellen":**  Fatal error: Uncaught Error: Call to a member function bind_param() on boolean in /app/public/project/newproject/index.php:16 Stack trace: #0 {main} thrown in /app/public/project/newproject/index.php on line 16
-Rest läuft fehlerfrei
