### ISSUE TITLE
Wechsel der Wochenansicht

### ISSUE THREAD

**Issue by PowerOfCreation** [PowerOfCreation/E1Ressourcenverwaltung#66]
Ziel: Es soll eine Möglichkeit geben, um die angezeigte Woche auf der Kalenderansicht umzuschalten. Sinnvoll dafür wären zwei Buttons, um zur vorherigen oder nächsten Woche zu wechseln. Alle Status müssen durch die richtigen Status der neu angezeigten Woche ersetzt werden und die Daten sowie die Kalenderwochennummer.
Wo: index.php und weekly-report.js

**Comment by Vinh911** [comment]
<img width="506" alt="Screen Shot 2022-05-27 at 17 53 05" src="https://user-images.githubusercontent.com/49061616/170734932-ee0e0e30-f636-4d18-a7dc-739becd4934a.png">
Für den Wechsel der Wochenansicht versuche ich gerade die aktuelle Kalenderwoche über die get_calendar_week.php api zu bekommen und in einer globalen Variable zu speichern.
Wenn ich mir das aber in der Konsole ausgeben lasse, kommt nur undefined. hat jemand von euch eine Idee wieso??

**Comment by PowerOfCreation** [comment]
Globale Variablen würde ich versuchen zu vermeiden. Wofür möchtest du die denn verwenden? Um seine globale Variable in einem anderem scope verwenden zu können muss das keyword global verwendet werden. Bsp.:

```
$test = 5;

fun myFun() {
  global $test;
  
  $test = 4;
}
```

**Comment by Vinh911** [comment]
> Globale Variablen würde ich versuchen zu vermeiden. Wofür möchtest du die denn verwenden? Um eine globale Variable in einem anderem scope verwenden zu können muss das keyword global verwendet werden. Bsp.:
> 
> ```
> $test = 5;
> 
> function myFun() {
>   global $test;
>   
>   $test = 4;
> }
> ```
> 
> https://www.php.net/manual/en/language.variables.scope.php

Mein Plan war es beim aufrufen der Seite eine globale Variable im weekly-report.js mit der aktuellen Kalenderwoche zu haben, damit man beim Wochenwechsel als Parameter die aktuell angezeigte Kalenderwoche +1, bzw -1  als Parameter an get_all_weekly_status.php weiter gibt.

**Comment by PowerOfCreation** [comment]
Ahh okay. Sorry dachte das wäre PHP Code aus irgendwelchen Gründen. Probier mal var statt let

**Comment by PowerOfCreation** [comment]
Ich würde dir aber davon abraten das so zu machen. Da bei jedem Status einfügen die Seite neugeladen wird sind die Werte dann natürlich auch weg. Am wenigsten Aufwand wäre die Kalenderwoche default auf die aktuelle zu setzen und sonst über einen GET Parameter überschreiben lassen. Bei jedem Wochenwechsel wird dann die Seite mit einem anderem GET Paramter neugeladen
