### ISSUE TITLE
Bug: Falsche Kalenderwoche + Datum wird angezeigt

### ISSUE THREAD

**Issue by PowerOfCreation** [PowerOfCreation/E1Ressourcenverwaltung#69]
Beheben: Status + Datum + Kalenderwoche werden falsch angezeigt auf der Wochenansicht.

**Comment by Vinh911** [comment]
Hehe #69

**Comment by PowerOfCreation** [comment]
Der Bug tritt nur auf wenn es gerade Montag ist? Bitte überprüfen.

**Comment by Vinh911** [comment]
> Der Bug tritt nur auf wenn es gerade Montag ist? Bitte überprüfen.

Ich kann es gerade nicht reproduzieren. Behalte es im Auge

**Comment by PowerOfCreation** [comment]
> > Der Bug tritt nur auf wenn es gerade Montag ist? Bitte überprüfen.
> 
> Ich kann es gerade nicht reproduzieren. Behalte es im Auge

Auch nicht wenn man die Systemzeit auf einen Montag stellt?

**Comment by PowerOfCreation** [comment]
@Vinh911 fehler besteht

**Comment by PowerOfCreation** [comment]
#82
