### ISSUE TITLE
Status hinzufügen

### ISSUE THREAD

**Issue by PowerOfCreation** [PowerOfCreation/E1Ressourcenverwaltung#71]
Ziel: Bei Auswahl eines Projektes in der Wochenansicht soll ein neuer Status angelegt werden:
![image](https://user-images.githubusercontent.com/24482177/168657497-86756a68-550c-4fb2-aa78-61abc2c30643.png)

Dazu soll die API [api/add_status.php](https://github.com/PowerOfCreation/E1Ressourcenverwaltung/blob/main/src/webserver/api/add_status.php) mit AJAX aufgerufen werden und der neu eingefügte Status angezeigt werden.

**Comment by PowerOfCreation** [comment]
Ja, sollte es. Kannst du probieren die Tabelle User_Project zu löschen und die Seite neuzuladen, sodass neue Werte in die Tabelle eingefügt werden? Bei mir funktioniert es auf dem main branch

**Comment by Vinh911** [comment]
<img width="1372" alt="Screen Shot 2022-05-18 at 14 41 18" src="https://user-images.githubusercontent.com/49061616/169040965-fd96163e-9776-4948-a507-a9589a42375a.png">
Ich muss bei dem option ding quasi ein onClick=()=>{addStatus()} einfügen ?

**Comment by PowerOfCreation** [comment]
Zum Beispiel, ja. Geht der dropdown jetzt?

**Comment by Vinh911** [comment]
> 

ja, ich war nur stupid haha

**Comment by Vinh911** [comment]
Irgendwie schwieriger als gedacht.
Ich rufe jetzt eine Funktion auf, wenn ein Projekt ausgewählt worden ist. Jetzt brauche ich aber die ID des Mitarbeiters und das Datum.
Können wir nachdem wir Status hinzufügen geklickt haben nicht ein neues Fenster öffnen, in der User, Project und Date ausgewählt wird? Wäre auf jedenfalls umumständlicher als jetzt so, da ich Datum und UserId nochmal Mappen müsste.

**Comment by Vinh911** [comment]
Soll ich dann erstmal warten bis das issue mit den PK fertig ist?

**Comment by PowerOfCreation** [comment]
Die API zum hinzufügen(add_status.php) sollte sich nach außen nicht verändern denke ich, also das betrifft dieses Issue nicht, außer ich habe etwas übersehen

**Comment by Vinh911** [comment]
Wer hat diese Abfrage geschrieben?

<img width="683" alt="Screen Shot 2022-05-20 at 17 03 58" src="https://user-images.githubusercontent.com/49061616/169556930-667ec40d-f9fb-4e4d-9ace-32fc3f22ef6f.png">

**Comment by PowerOfCreation** [comment]
Wo steht die denn? Musst du ggf ein git blame machen. Vom drüberschauen sieht die Abfrage gut aus und müsste funktionieren. Wird so eine ähnliche Abfrage nicht auch zum Status hinzufügen verwendet? Da bekommt man ja mehrere Projekte zurückgeliefert.

**Comment by Vinh911** [comment]
> Wo steht die denn? Musst du ggf ein git blame machen. Vom drüberschauen sieht die Abfrage gut aus und müsste funktionieren. Wird so eine ähnliche Abfrage nicht auch zum Status hinzufügen verwendet? Da bekommt man ja mehrere Projekte zurückgeliefert.

Ich hab gerade ein bisschen getestet. Nicht die Abfrage ist das Problem, sondern wenn ich ein Projekt erstelle, wird kein Eintrag in der User_Project Tabelle erstellt. Fehl das noch, oder ist es gerade buggy?

**Comment by PowerOfCreation** [comment]
Ich glaube dafür gibt's ein issue

**Comment by Vinh911** [comment]
#74
