### ISSUE TITLE
Lizenz für Projekt erarbeiten

### ISSUE THREAD

**Issue by s82068** [PowerOfCreation/E1Ressourcenverwaltung#84]
Durch die verwendeten Tools beim Programmieren ist unser Programm verschiedenen "Lizenzeinschränkungen" unterlegen (PDF Seite 6)
https://choosealicense.com/ als Hilfe kann dies dienen

**Comment by PowerOfCreation** [comment]
Hinweis: choosealicense ist da um eine Lizenz auszuwählen für die eigene Software. Das wollen wir hier gar nicht machen(vermute ich mal stark), da wir da nicht mitzureden haben. Wir entwickeln für den Themensteller und er kann sich die Lizenz aussuchen.

Ich denke es geht darum das wir uns mit den Lizenzen von Software auseinandersetzen müssen, welche WIR verwenden also z.B. Docker/PHP/jQuery. Diese Lizenzen müssen herausgesucht werden und in ein Lizenzdatei kopiert werden. Da wir diese Software verwendet haben unterliegt unsere Software ebenfalls einigen Regelungen und an diese muss sich auch der Themensteller halten.
