### ISSUE TITLE
Projektverwaltung: Projekte löschen

### ISSUE THREAD

**Issue by PowerOfCreation** [PowerOfCreation/E1Ressourcenverwaltung#94]
Ziel: In der Projektansicht soll es möglich sein ein Projekt anzuwählen und durch einen Button dieses Projekt zu löschen. Das löschen soll mit noch einmal bestätigt werden(https://stackoverflow.com/questions/9334636/how-to-create-a-dialog-with-ok-and-cancel-options). Bestätigt der Nutzer soll via Ajax(Method: Delete https://www.educba.com/jquery-ajax-delete/ ) ein neuer PHP-Endpunkt aufgerufen werden, dem die Projekt-Id übergeben wird. Dieser löscht dann sämtliche Status mit diesem Projekt und anschließend das Projekt.

Wo: erweitern der projektverwaltung in webserver/project + neuer api endpunkt in webserver/api/projects/index.php mit REST API. Die REST-API soll nur DELETE unterstützten und nichts weiter. Wie man eine REST API mit PUT, DELETE und GET aufbaut kann man sich dazu in webserver/api/projects/employees/index.php anschauen

**Comment by Vinh911** [comment]
/api/projects/employee/index.php:
im switch case statement gibt es bereits den case "DELETE". Der sollte quasi mal sowas ähnliches machen, wenn ich das richtig sehe.
Den kann ich löschen und den Code für 
löschen aller Einträge mit matching ProjectId in Tabelle Status, Project und User_Project
nochmal neu schreiben?

**Comment by PowerOfCreation** [comment]
Der bestehende Code da funktioniert und ist für das hinzufügen/löschen von Mitarbeitern zu einem Projekt. Jetzt brauchen wir noch etwas um Projekte zu löschen. Du kannst dich da an der bestehenden Datei orientieren

**Comment by Vinh911** [comment]
> Der bestehende Code da funktioniert und ist für das hinzufügen/löschen von Mitarbeitern zu einem Projekt. Jetzt brauchen wir noch etwas um Projekte zu löschen. Du kannst dich da an der bestehenden Datei orientieren

Aber das Projekt löschen kommt mit in das Switch Statement, oder erstell ich ein neues Switch Case?

**Comment by PowerOfCreation** [comment]
Die Datei die du genannt hast macht wie gesagt etwas anderes. An der
solltest du gar nichts editieren oder welches Switch statement meinst du?

**Comment by Vinh911** [comment]
hab gerade gesehen, da ist noch ein Zwischenordner  employee ^^

**Comment by Vinh911** [comment]
#120
