### ISSUE TITLE
Wochenansicht: Löschen eines Status

### ISSUE THREAD

**Issue by PowerOfCreation** [PowerOfCreation/E1Ressourcenverwaltung#98]
Ziel: Wenn über einen Status mit der Maus gefahren wird, dann soll in der Zeile des Status ein Kreuz eingeblendet werden und wird dieses gedrückt, dann soll der Status entfernt werden. Dies soll mit Ajax realisiert werden. Optional kann eine Bestätigung eingebaut werden: https://www.w3schools.com/js/js_popup.asp. 
Wo: weekly-report.js

Hinweis: Es muss dafür ein neuer API-Endpunkt definiert werden. Dies könnte zum Beispiel in einer neuen Datei webserver/api/remove_status.php passieren. Der Code sollte sehr ähnlich zu webserver/api/add_status.php sein.

**Comment by Vinh911** [comment]
Hier sollte auch Status hinzufügen deaktivieren werden, wenn es schon einen Status für diesen Tag gibt.

**Comment by Vinh911** [comment]
#121
